export const ADD_TODO = 'ADD_TODO'
export const TOGGLE_TODO = 'TOGGLE_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const FETCH_TODO = 'FETCH_TODO'
export const SELECT_FILTER = 'SELECT_FILTER'
